root: "credentials"
schemas:
  credentials:
    type: "dict"
    props:
      vpn:
        schema: "digital_ocean_vpn_credentials"
        non_empty: true
  digital_ocean_vpn_credentials:
    type: "dict"
    props:
      api_token:
        type: "str"
        non_empty: true
