- name: "{{ cloud_service_title | default('') }} - vpn - digital ocean"
  set_fact:
    cloud_service_vpn_title: "{{ cloud_service_title }} - vpn - digital ocean"
  tags: ["no_print"]

- name: "{{ cloud_service_vpn_title }} - cloud_service_vpn_tags"
  set_fact:
    cloud_service_vpn_state: "{{ cloud_service_state | default('present', true) }}"
    cloud_service_vpn_tags: >-
      {{ cloud_service_params.tags | default([]) }}
    cloud_service_vpn_firewalls_list: >-
      {{ cloud_service_params.firewalls | default([]) }}
    cloud_service_vpn_firewalls_dict: >-
      {{ cloud_service_params.firewalls_dict | default({}) }}
    cloud_service_vpn_firewalls: []
  tags: ["no_print"]

- name: "{{ cloud_service_vpn_title }} - cloud_service_vpn_firewalls"
  set_fact:
    cloud_service_vpn_firewalls: >-
      {{ cloud_service_vpn_firewalls + [cloud_service_vpn_firewall] }}
  vars:
    cloud_service_vpn_firewall: >-
      {{
        cloud_service_params.meta.use_dict | default(false) | bool
        | ternary(
          cloud_service_vpn_firewalls_dict[cloud_service_vpn_item],
          cloud_service_vpn_item
        )
      }}
  loop: "{{ cloud_service_vpn_firewalls_list }}"
  loop_control:
    loop_var: cloud_service_vpn_item
    label: "{{ cloud_service_vpn_firewall.name | default('') }}"
  tags: ["no_print"]

- name: "{{ cloud_service_vpn_title }} - block"
  block:
    - name: "{{ cloud_service_vpn_title }} - cloud_service_vpn_tags_final - init"
      set_fact:
        cloud_service_vpn_tags_final: []
      tags: ["no_print"]

    - name: "{{ cloud_service_vpn_title }} - cloud_service_vpn_tags_final - fill"
      set_fact:
        cloud_service_vpn_tags_final: >-
          {{ cloud_service_vpn_tags_final + [cloud_service_vpn_item] }}
      loop: "{{ cloud_service_vpn_tags | default([]) }}"
      loop_control:
        loop_var: cloud_service_vpn_item
      tags: ["no_print"]

    - name: >-
        {{ cloud_service_vpn_title }} -
        {{ (cloud_service_vpn_state == 'present') | ternary('create', 'destroy')}}
        tags
      digital_ocean_tag:
        api_token: "{{ cloud_service_credentials.api_token | default('') }}"
        name: "{{ cloud_service_vpn_item }}"
        state: "{{ cloud_service_vpn_state }}"
      loop: "{{ cloud_service_vpn_tags_final | default([]) }}"
      loop_control:
        loop_var: cloud_service_vpn_item

  when: (cloud_service_vpn_tags | default([])) | length > 0
  tags: ["no_print_skipped"]

- block:
    - name: "{{ cloud_service_vpn_title }} - cloud_service_vpn_firewalls_final - init"
      set_fact:
        cloud_service_vpn_firewalls_final: []
      tags: ["no_print"]

    - name: "{{ cloud_service_vpn_title }} - cloud_service_vpn_firewalls_final - fill (outer)"
      include_tasks: "digital_ocean.firewall_tags.yml"
      vars:
        cloud_service_vpn_firewall_title: >-
          {{ cloud_service_vpn_title }} - firewall tags
          [{{ cloud_service_vpn_firewall.name | default('') }}]
        cloud_service_vpn_firewall: "{{ cloud_service_vpn_item }}"
      loop: "{{ cloud_service_vpn_firewalls | default([]) }}"
      loop_control:
        loop_var: cloud_service_vpn_item
        label: "{{ cloud_service_vpn_firewall.name | default('') }}"
      tags: ["no_print"]

    - name: >-
        {{ cloud_service_vpn_title }} -
        {{ (cloud_service_vpn_state == 'present') | ternary('create', 'destroy')}}
        firewalls
      digital_ocean_firewall:
        api_token: "{{ cloud_service_credentials.api_token | default('') }}"
        name: "{{ cloud_service_vpn_item.name }}"
        droplet_ids: "{{ cloud_service_vpn_item.droplet_ids | default([]) }}"
        tags: "{{ cloud_service_vpn_item.tags | default([]) }}"
        inbound_rules: "{{ cloud_service_vpn_item.inbound_rules | default([]) }}"
        outbound_rules: "{{ cloud_service_vpn_item.outbound_rules | default([]) }}"
        state: "{{ cloud_service_vpn_state }}"
      loop: "{{ cloud_service_vpn_firewalls_final | default([]) }}"
      loop_control:
        loop_var: cloud_service_vpn_item
        label: "{{ cloud_service_vpn_item.name }}"
      tags: ["no_print_skipped"]

  when: (cloud_service_vpn_firewalls | default([])) | length > 0
  tags: ["no_print_skipped"]
