# Prepare

- name: "{{ inner_service_title }} - vpn - digital ocean - vars"
  set_fact:
    ext_vpn_title: "{{ inner_service_title }} - vpn - digital ocean"
    ext_vpn_params: "{{ inner_service_params }}"
    ext_vpn_credentials: "{{ inner_service_credentials }}"
    ext_vpn_contents: "{{ inner_service_contents }}"
    ext_vpn_state: "{{ inner_service_state }}"
    ext_vpn_base_dir_prefix: "{{ inner_service_base_dir_prefix }}"
    ext_vpn_tmp_dir: "{{ inner_service_tmp_dir }}"
    ext_vpn_result: {}
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

# Main

- name: "{{ ext_vpn_title }} - ext_vpn_main_credentials"
  set_fact:
    ext_vpn_main_credentials: "{{ tmp_credentials }}"
    ext_vpn_tags: >-
      {{ ext_vpn_params.tags | default([]) }}
    ext_vpn_firewalls: >-
      {{ ext_vpn_params.firewalls | default([]) }}
    ext_vpn_api_token: >-
      {{ tmp_credentials.api_token | default('') }}
  vars:
    tmp_credentials: "{{ ext_vpn_credentials.vpn | default({}) }}"
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "(test) create a firewall named my_firewall"
  lrd.ext_cloud.digital_ocean_firewall:
    api_token: "{{ ext_vpn_api_token }}"
    name: my-firewall
    state: present
    inbound_rules:
      - protocol: "tcp"
        ports: "22"
        sources:
          addresses: ["1.2.3.4"]
          droplet_ids: ["123456", "1234556"]
          load_balancer_uids: ["111222", "333444"]
          tags: ["tag-1", "tag-2"]
      - protocol: "tcp"
        ports: "80"
        sources:
          addresses: ["0.0.0.0/0", "::/0"]
      - protocol: "tcp"
        ports: "443"
        sources:
          addresses: ["0.0.0.0/0", "::/0"]
    outbound_rules:
      - protocol: "tcp"
        ports: "1-65535"
        destinations:
          addresses: ["0.0.0.0/0", "::/0"]
      - protocol: "udp"
        ports: "1-65535"
        destinations:
          addresses: ["0.0.0.0/0", "::/0"]
      - protocol: "icmp"
        ports: "1-65535"
        destinations:
          addresses: ["0.0.0.0/0", "::/0"]
    droplet_ids: ["555666", "777888"]
    tags: ["sample"]

- name: >-
    {{ ext_vpn_title }} -
    {{ (ext_vpn_state == 'present') | ternary('create', 'destroy')}}
    tags
  digital_ocean_tag:
    api_token: "{{ ext_vpn_api_token }}"
    name: "{{ ext_vpn_item }}"
    state: "{{ ext_vpn_state }}"
  loop: "{{ ext_vpn_tags | default([]) }}"
  loop_control:
    loop_var: ext_vpn_item
  no_log: "{{ env_no_log }}"

- name: >-
    {{ ext_vpn_title }} -
    {{ (ext_vpn_state == 'present') | ternary('create', 'destroy')}}
    firewalls
  lrd.ext_cloud.digital_ocean_firewall:
    api_token: "{{ ext_vpn_api_token }}"
    name: "{{ ext_vpn_item.name }}"
    droplet_ids: "{{ ext_vpn_item.droplet_ids | default([]) }}"
    tags: "{{ ext_vpn_item.tags | default([]) }}"
    inbound_rules: "{{ ext_vpn_item.inbound_rules | default([]) }}"
    outbound_rules: "{{ ext_vpn_item.outbound_rules | default([]) }}"
    state: "{{ ext_vpn_state }}"
  when: (ext_vpn_firewalls | default([])) | length > 0
  loop: "{{ ext_vpn_firewalls | default([]) }}"
  loop_control:
    loop_var: ext_vpn_item
    label: "{{ ext_vpn_item.name }}"
  no_log: "{{ env_no_log }}"
  tags: ["no_print_skipped"]
