- name: "{{ ext_vpn_firewall_title }} - ext_vpn_firewall_tags - init"
  set_fact:
    ext_vpn_firewall_tags: []
  tags: ["no_print"]

- name: "{{ ext_vpn_firewall_title }} - ext_vpn_firewall_tags - fill"
  set_fact:
    ext_vpn_firewall_tags: >-
      {{ ext_vpn_firewall_tags + [ext_vpn_tag_item] }}
  loop: "{{ ext_vpn_firewall.tags | default([]) }}"
  loop_control:
    loop_var: ext_vpn_tag_item
  tags: ["no_print"]

- name: "{{ ext_vpn_firewall_title }} - ext_vpn_firewall_result"
  set_fact:
    ext_vpn_firewall_result: >-
      {{
        ext_vpn_firewall
        | combine({
          'name': ext_vpn_firewall.name,
          'tags': ext_vpn_firewall_tags
        })
      }}
  tags: ["no_print"]

- name: "{{ ext_vpn_firewall_title }} - ext_vpn_firewalls_final"
  set_fact:
    ext_vpn_firewalls_final: >-
      {{ ext_vpn_firewalls_final + [ext_vpn_firewall_result] }}
  tags: ["no_print"]
