- name: "{{ ext_vpn_title }} - ext_vpn_main_credentials"
  set_fact:
    ext_vpn_main_credentials: "{{ ext_vpn_credentials.vpn | default({}) }}"
  tags: ["no_print"]

- name: "{{ ext_vpn_title }} - ext_vpn_tags"
  set_fact:
    ext_vpn_tags: >-
      {{ ext_vpn_params.tags | default([]) }}
    ext_vpn_firewalls: >-
      {{ ext_vpn_params.firewalls | default([]) }}
    ext_vpn_api_token: >-
      {{ ext_vpn_main_credentials.api_token | default('') }}
  tags: ["no_print"]

- name: >-
    {{ ext_vpn_title }} -
    {{ (ext_vpn_state == 'present') | ternary('create', 'destroy')}}
    tags
  digital_ocean_tag:
    api_token: "{{ ext_vpn_api_token }}"
    name: "{{ ext_vpn_item }}"
    state: "{{ ext_vpn_state }}"
  loop: "{{ ext_vpn_tags | default([]) }}"
  loop_control:
    loop_var: ext_vpn_item

- name: "{{ ext_vpn_title }} - block - firewalls"
  block:
    - name: "{{ ext_vpn_title }} - ext_vpn_firewalls_final - init"
      set_fact:
        ext_vpn_firewalls_final: []
      tags: ["no_print"]

    - name: "{{ ext_vpn_title }} - ext_vpn_firewalls_final - fill (outer)"
      include_tasks: "digital_ocean.firewall_tags.vpn.yml"
      vars:
        ext_vpn_firewall_title: >-
          {{ ext_vpn_title }} - firewall tags
          [{{ ext_vpn_firewall.name | default('') }}]
        ext_vpn_firewall: "{{ ext_vpn_item }}"
      loop: "{{ ext_vpn_firewalls | default([]) }}"
      loop_control:
        loop_var: ext_vpn_item
        label: "{{ ext_vpn_firewall.name | default('') }}"
      tags: ["no_print"]

    - name: >-
        {{ ext_vpn_title }} -
        {{ (ext_vpn_state == 'present') | ternary('create', 'destroy')}}
        firewalls
      digital_ocean_firewall:
        api_token: "{{ ext_vpn_api_token }}"
        name: "{{ ext_vpn_item.name }}"
        droplet_ids: "{{ ext_vpn_item.droplet_ids | default([]) }}"
        tags: "{{ ext_vpn_item.tags | default([]) }}"
        inbound_rules: "{{ ext_vpn_item.inbound_rules | default([]) }}"
        outbound_rules: "{{ ext_vpn_item.outbound_rules | default([]) }}"
        state: "{{ ext_vpn_state }}"
      loop: "{{ ext_vpn_firewalls_final | default([]) }}"
      loop_control:
        loop_var: ext_vpn_item
        label: "{{ ext_vpn_item.name }}"
      tags: ["no_print_skipped"]
  when: (ext_vpn_firewalls | default([])) | length > 0
  tags: ["no_print_skipped"]
