- set_fact:
    cloud_main_inner_firewall_tags: []
  tags: ["no_print"]

- set_fact:
    cloud_main_inner_firewall_tags: >-
      {{
      cloud_main_inner_firewall_tags +
      [cloud_main_inner_tag_item]
      }}
  loop: "{{ cloud_main_inner_firewall.tags | default([]) }}"
  loop_control:
    loop_var: cloud_main_inner_tag_item
  tags: ["no_print"]

- set_fact:
    cloud_main_inner_firewall_result: >-
      {{ 
      cloud_main_inner_firewall | 
      combine({ 
      'name': cloud_main_inner_firewall.name,
      'tags': cloud_main_inner_firewall_tags 
      }) 
      }}
  tags: ["no_print"]

- set_fact:
    cloud_main_inner_firewalls_final: >-
      {{
      cloud_main_inner_firewalls_final +
      [cloud_main_inner_firewall_result]
      }}  
  tags: ["no_print"]  