- set_fact:
    cloud_main_inner_tags: "{{ cloud_main_params.x_digital_ocean_tags | default([]) }}"
    cloud_main_inner_firewalls_list: >-
      {{ cloud_main_params.x_digital_ocean_firewalls | default([]) }}
    cloud_main_inner_firewalls_dict: >-
      {{ cloud_main_params.x_digital_ocean_firewalls_dict | default({}) }}
    cloud_main_inner_firewalls: []
  tags: ["no_print"]

- set_fact:
    cloud_main_inner_firewalls: >-
      {{ 
      cloud_main_inner_firewalls + 
      [cloud_main_inner_firewall] 
      }}
  vars:
    cloud_main_inner_firewall: >-
      {{
      cloud_main_params.meta.use_dict | default(false) | bool | ternary(
      cloud_main_inner_firewalls_dict[cloud_main_inner_item],
      cloud_main_inner_item)
      }}
  loop: "{{ cloud_main_inner_firewalls_list }}"
  loop_control:
    loop_var: cloud_main_inner_item
  tags: ["no_print"]

- block:
  - set_fact:
      cloud_main_inner_tags_final: []
    tags: ["no_print"]

  - set_fact:
      cloud_main_inner_tags_final: >-
        {{
        cloud_main_inner_tags_final +
        [cloud_main_inner_item]
        }}
    loop: "{{ cloud_main_inner_tags | default([]) }}"
    loop_control:
      loop_var: cloud_main_inner_item
    tags: ["no_print"]

  - name: >-
      {{ cloud_main_inner_title }} -
      {{ (cloud_main_state == 'present') | ternary('create', 'destroy')}}
      tags
    digital_ocean_tag:
      api_token: "{{ cloud_main_inner_api_token }}"
      name: "{{ cloud_main_inner_item }}"
      state: "{{ cloud_main_state }}"
    loop: "{{ cloud_main_inner_tags_final | default([]) }}"
    loop_control:
      loop_var: cloud_main_inner_item

  when: (cloud_main_inner_tags | default([])) | length > 0
  tags: ["no_print_skipped"]

- block:

  - set_fact:
      cloud_main_inner_firewalls_final: []
    tags: ["no_print"]

  - include_tasks: "digital_ocean.firewall_tags.yml"
    vars:
      cloud_main_inner_firewall: "{{ cloud_main_inner_item }}"
    loop: "{{ cloud_main_inner_firewalls | default([]) }}"
    loop_control:
      loop_var: cloud_main_inner_item
    tags: ["no_print"]

  - name: >-
      {{ cloud_main_inner_title }} -
      {{ (cloud_main_state == 'present') | ternary('create', 'destroy')}}
      firewalls
    digital_ocean_firewall:
      api_token: "{{ cloud_main_inner_api_token }}"
      name: "{{ cloud_main_inner_item.name }}"
      droplet_ids: "{{ cloud_main_inner_item.droplet_ids | default([]) }}"
      tags: "{{ cloud_main_inner_item.tags | default([]) }}"
      inbound_rules: "{{ cloud_main_inner_item.inbound_rules | default([]) }}"
      outbound_rules: "{{ cloud_main_inner_item.outbound_rules | default([]) }}"
      state: "{{ cloud_main_state }}"
    loop: "{{ cloud_main_inner_firewalls_final | default([]) }}"
    loop_control:
      loop_var: cloud_main_inner_item
      label: "{{ cloud_main_inner_item.name }}"
    tags: ["no_print_skipped"]

  when: (cloud_main_inner_firewalls | default([])) | length > 0
  tags: ["no_print_skipped"]
