- name: "{{ inner_service_title }} - godaddy nameserver - vars"
  lrd.ext_cloud.vars:
    identifier: "godaddy_nameserver"
    raw_data:
      namespace: "ext_nameserver"
      state: "{{ inner_service_state }}"
      params: "{{ inner_service_params }}"
      credentials: "{{ inner_service_credentials }}"
      contents: "{{ inner_service_contents }}"
  register: ext_nameserver_data_wrapper
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ inner_service_title }} - godaddy nameserver - action"
  lrd.ext_cloud.actions:
    identifier: "godaddy_nameserver"
    data: "{{ ext_nameserver_item }}"
  loop: "{{ ext_nameserver_data_wrapper.data.list }}"
  loop_control:
    loop_var: ext_nameserver_item
    label: "[{{ ext_nameserver_item.state }}] {{ ext_nameserver_item.zone }}"
  no_log: "{{ env_no_log }}"
