root: "credentials"
schemas:
  credentials:
    type: "dict"
    props:
      s3:
        schema: "s3_credentials"
        non_empty: true
  s3_credentials:
    type: "dict"
    props:
      host:
        type: "str"
      ssl:
        type: "bool"
      endpoint:
        type: "str"
      access_key:
        type: "str"
        non_empty: true
      secret_key:
        type: "str"
        non_empty: true
