root: "s3_schema"
schemas:
  s3_schema:
    type: "dict"
    description: "schema for the s3 task"
    props:
      params:
        schema: "params"
        non_empty: true
        description: "parameters for the s3 task"
      credentials:
        schema: "credentials"
        non_empty: true
        description: "credentials for the s3 task"
  params:
    type: "dict"
    description: "parameters schema for the s3 task"
    props:
      bucket:
        type: "str"
        non_empty: true
        description: "s3 bucket name"
      permission:
        type: "str"
        choices:
          - "private"
          - "public-read"
          - "public-read-write"
          - "authenticated-read"
        description: "s3 bucket permission"
  credentials:
    type: "map"
    elem_key_regex: "^[-\\w]+$"
    elem_schema: "s3_credentials"
    description: "credentials schema dictionary for the s3 task"
  s3_credentials:
    type: "dict"
    description: "s3 credentials schema"
    props:
      endpoint:
        type: "str"
        description: "s3 host (url endpoint; uses aws by default)"
      access_key:
        type: "str"
        non_empty: true
        description: "s3 access key"
      secret_key:
        type: "str"
        non_empty: true
        description: "s3 secret key"
