root: "digital_ocean_node_params"
schemas:
  digital_ocean_node_params:
    type: "dict"
    props:
      name:
        type: "str"
        non_empty: true
      state:
        type: "str"
        choices: ["present", "absent"]
      region_id:
        type: "str"
        non_empty: true
      size_id:
        type: "str"
        non_empty: true
      image_id:
        type: "str"
        non_empty: true
      wait_timeout:
        type: "int"
      ipv6:
        type: "bool"
      user_data:
        schema: "content"
      tags:
        type: "list"
        elem_type: "str"
        elem_non_empty: true
  content:
    type: "simple_dict"
    alternative_type: "str"
    props:
      type:
        type: "str"
        choices: ["env", "str", "file", "template"]
      name:
        type: "str"
      key:
        type: "str"
      origin:
        type: "str"
      file:
        type: "str"
      params_schema:
        type: "str"
      credentials_schema:
        type: "str"
      credentials:
        type: "map"
        elem_type: "str"
      params:
        type: "dict"
      group_params:
        type: "map"
        elem_type: "str"
      shared_params:
        type: "list"
        elem_type: "str"
      shared_group_params:
        type: "str"
