- set_fact: 
    cloud_node_item_name: "{{ cloud_node_item.name | replace('_', '-') }}"
  tags: ["no_print"]

- name: >-
    {{ cloud_node_inner_title }} -
    {{ cloud_node_inner_create | bool | ternary('create', 'destroy') }}
    droplet - {{ cloud_node_item_name }}
  digital_ocean_droplet:
    unique_name: yes
    oauth_token: "{{ cloud_node_inner_api_token }}"
    name: "{{ cloud_node_item_name }}"
    state: "{{ cloud_node_inner_create | bool | ternary('present', 'absent') }}"
    region_id: "{{ cloud_node_item.region_id }}"
    size_id: "{{ cloud_node_inner_size_id }}"
    image_id: "{{ cloud_node_inner_image_id }}"
    wait_timeout: "{{ cloud_node_inner_wait_timeout }}"
    private_networking: "true"
    ipv6: "{{ cloud_node_inner_ipv6 | default(omit) }}"
    user_data: "{{ cloud_node_inner_user_data }}"
  register: cloud_node_inner_details
  tags: ["no_print_skipped"]

- block:

  - set_fact: 
      cloud_node_inner_droplet: "{{ cloud_node_inner_details.data.droplet }}"
    tags: ["no_print"]
  
  - name: >-
      {{ cloud_node_inner_title }} - tag the droplet {{ cloud_node_item_name }}
    digital_ocean_tag:
      api_token: "{{ cloud_node_inner_api_token }}"
      resource_id: "{{ cloud_node_inner_droplet.id }}"
      name: "{{ cloud_node_inner_item }}"
      state: "present"
    loop: "{{ cloud_node_inner_params.x_digital_ocean_tags }}"
    loop_control:
      loop_var: cloud_node_inner_item
      label: "{{ cloud_node_item_name }} - {{ cloud_node_inner_item }}"
    tags: ["no_print_skipped"]
    
  - set_fact: 
      cloud_node_inner_host: 
        name: "{{ cloud_node_item_name }}"
        private_ip: >-
          {{ 
          (cloud_node_inner_droplet.networks.v4 |
          selectattr('type', 'equalto', 'private') |
          map(attribute='ip_address') | list | first | default(''))
          }}
        public_ipv4: >-
          {{ 
          (cloud_node_inner_droplet.networks.v4 |
          selectattr('type', 'equalto', 'public') |
          map(attribute='ip_address') | list | first | default(''))
          }}
        public_ipv6: >-
          {{ 
          (cloud_node_inner_droplet.networks.v6 |
          selectattr('type', 'equalto', 'public') |
          map(attribute='ip_address') | list | first | default(''))
          }}
    tags: ["no_print"]
      
  - set_fact: 
      cloud_node_active_hosts: "{{ cloud_node_active_hosts + [cloud_node_inner_host] }}"
    tags: ["no_print"]

  when: cloud_node_inner_create | bool
  tags: ["no_print_skipped"]