- name: >-
    {{ ext_node_item_title }} - {{ ext_node_item_instance_state }}
    droplet - {{ ext_node_item_name }}
  digital_ocean_droplet:
    unique_name: yes
    oauth_token: "{{ ext_node_main_credentials.api_token }}"
    name: "{{ ext_node_item_name }}"
    state: "{{ ext_node_item_instance_state }}"
    region_id: "{{ ext_node_params.region_id }}"
    size_id: "{{ ext_node_params.size_id }}"
    image_id: "{{ ext_node_params.image_id }}"
    wait_timeout: "{{ ext_node_params.wait_timeout | default(300, true) }}"
    private_networking: "true"
    ipv6: "{{ ext_node_params.ipv6 | default(omit, true) }}"
    user_data: "{{ ext_node_user_data | default(omit, true) }}"
  register: ext_node_item_details
  tags: ["no_print_skipped"]

- name: "{{ ext_node_item_title }} - ext_node_item_droplet"
  set_fact:
    ext_node_item_droplet: "{{ ext_node_details.data.droplet }}"
  tags: ["no_print"]

- name: >-
    {{ ext_node_item_title }} - tag the droplet {{ ext_node_item_name }}
  digital_ocean_tag:
    api_token: "{{ ext_node_main_credentials.api_token }}"
    resource_id: "{{ ext_node_item_droplet.id }}"
    name: "{{ ext_node_item_inner }}"
    state: "present"
  loop: "{{ ext_node_params.tags }}"
  loop_control:
    loop_var: ext_node_item_inner
    label: "{{ ext_node_item_name }} - {{ ext_node_item_inner }}"
  when: ext_node_item_instance_state == 'present'
  tags: ["no_print_skipped"]

- name: "{{ ext_node_item_title }} - set result (tmp)"
  set_fact:
    ext_node_item_result:
      name: "{{ ext_node_item_name }}"
      state: "{{ ext_node_item_instance_state }}"
      private_ip: >-
        {{
          ext_node_item_droplet.networks.v4
          | default({})
          | selectattr('type', 'defined')
          | selectattr('type', 'equalto', 'private')
          | selectattr('ip_address', 'defined')
          | map(attribute='ip_address') | list | first | default('')
        }}
      public_ipv4: >-
        {{
          ext_node_item_droplet.networks.v4
          | default({})
          | selectattr('type', 'defined')
          | selectattr('type', 'equalto', 'public')
          | selectattr('ip_address', 'defined')
          | map(attribute='ip_address') | list | first | default('')
        }}
      public_ipv6: >-
        {{
          ext_node_item_droplet.networks.v6
          | default({})
          | selectattr('type', 'defined')
          | selectattr('type', 'equalto', 'public')
          | selectattr('ip_address', 'defined')
          | map(attribute='ip_address') | list | first | default('')
        }}
  tags: ["no_print"]

- name: "{{ ext_node_item_title }} - ext_node_hosts"
  set_fact:
    ext_node_hosts: "{{ ext_node_hosts + [ext_node_item_result] }}"
  tags: ["no_print"]
