root: "node_schema"
schemas:
  node_schema:
    type: "dict"
    props:
      params:
        schema: "params"
        non_empty: true
      credentials:
        schema: "credentials"
        non_empty: true
      contents:
        schema: "contents"
  params:
    type: "dict"
    props:
      replicas:
        type: "list"
        elem_schema: "replica"
        required: true
      region_id:
        type: "str"
        non_empty: true
      size_id:
        type: "str"
        non_empty: true
      image_id:
        type: "str"
        non_empty: true
      wait_timeout:
        type: "int"
      ipv6:
        type: "bool"
      tags:
        type: "list"
        elem_type: "str"
        elem_non_empty: true
  replica:
    type: "dict"
    props:
      name:
        type: "str"
        non_empty: true
      absent:
        type: "bool"
  credentials:
    type: "dict"
    props:
      node:
        schema: "digital_ocean_credentials"
        non_empty: true
  digital_ocean_credentials:
    type: "dict"
    props:
      api_token:
        type: "str"
        non_empty: true
  contents:
    type: "dict"
    props:
      user_data:
        type: "str"
