# Prepare

- name: "{{ inner_service_title }} - node - linode - vars"
  set_fact:
    ext_node_title: "{{ inner_service_title }} - node - linode"
    ext_node_params: "{{ inner_service_params }}"
    ext_node_credentials: "{{ inner_service_credentials }}"
    ext_node_contents: "{{ inner_service_contents }}"
    ext_node_state: "{{ inner_service_state }}"
    ext_node_base_dir_prefix: "{{ inner_service_base_dir_prefix }}"
    ext_node_tmp_dir: "{{ inner_service_tmp_dir }}"
    ext_node_result: {}
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

# Node Main Vars

- name: "{{ ext_node_title }} - main vars"
  set_fact:
    ext_node_main_credentials: "{{ ext_node_credentials.node | default({}) }}"
    ext_node_user_data: "{{ ext_node_contents.user_data | default('') }}"
    ext_node_hosts: []
    ext_node_state_description: >-
      {{
        (ext_node_state == 'present')
        | ternary('create', 'delete')
      }}
    ext_node_stackscript_details: {}
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

# Main

- name: "{{ ext_node_title }} - manage stackscript ({{ ext_node_state_description }})"
  lrd.ext_cloud.actions:
    identifier: "linode_stackscript"
    data:
      label: "{{ ext_node_params.name }}-stackscript"
      state: "{{ ext_node_state }}"
      api_token: "{{ ext_node_main_credentials.api_token }}"
      description: "{{ ext_node_params.stackscript.description | default(omit, true) }}"
      images: "{{ ext_node_params.stackscript.images | default([ext_node_params.image], true) }}"
      is_public: "{{ ext_node_params.stackscript.is_public | default(omit, true) }}"
      rev_note: "{{ ext_node_params.stackscript.rev_note | default(omit, true) }}"
      script: "{{ ext_node_contents.user_data }}"
  register: ext_node_stackscript_details
  when: (ext_node_contents.user_data | default('')) != ''
  no_log: "{{ env_no_log }}"
  tags: ["no_print_skipped"]

- name: "{{ ext_node_title }} - instances"
  linode_v4:
    label: "{{ ext_node_item_name }}"
    state: "{{ ext_node_item_state }}"
    access_token: "{{ ext_node_main_credentials.api_token }}"
    type: "{{ ext_node_params.type }}"
    region: "{{ ext_node_params.region }}"
    image: "{{ ext_node_params.image }}"
    root_pass: "{{ ext_node_credentials.root.pass | default(omit, true) }}"
    authorized_keys: "{{ ext_node_keys }}"
    stackscript_id: "{{ ext_node_stackscript_details.data.id | default(omit, true) }}"
    stackscript_data: "{{ ext_node_params.stackscript_data | default(omit, true) }}"
    tags: "{{ ext_node_params.tags | default(omit, true) }}"
  vars:
    ext_node_item_name: "{{ ext_node_item.name }}"
    ext_node_item_state: >-
      {{
        ext_node_item.absent
        | default(false)
        | ternary('absent', ext_node_state)
      }}
    ext_node_keys_str: "{{ ext_node_contents.authorized_keys | default('') }}"
    ext_node_keys: "{{ (ext_node_keys_str != '') | ternary(ext_node_keys_str.split('\n'), []) }}"
  loop: "{{ ext_node_params.replicas }}"
  loop_control:
    loop_var: ext_node_item
    label: "{{ ext_node_item_name }} ({{ ext_node_item_state }})"
  register: ext_node_details
  no_log: "{{ env_no_log }}"

- name: "{{ ext_node_item_title }} - set result (tmp)"
  set_fact:
    ext_node_hosts: "{{ ext_node_hosts + [ext_node_item_result] }}"
  vars:
    ext_node_item: "{{ ext_node_item_data[ext_node_item_data.ansible_loop_var] | default({}) }}"
    ext_node_instance: "{{ ext_node_item_data.instance | default({}) }}"
    ext_node_item_name: "{{ ext_node_item.name | default('') }}"
    ext_node_item_state: >-
      {{
        ext_node_item.absent
        | default(false)
        | ternary('absent', ext_node_state)
      }}
    ext_node_item_result:
      name: "{{ ext_node_item_name }}"
      state: "{{ ext_node_item_state }}"
      private_ip: ""
      public_ipv4: "{{ ext_node_instance.ipv4[0] | default('') }}"
      public_ipv6: "{{ ext_node_instance.ipv6 | default('') | regex_replace('(.*)/(.*)', '\\1') }}"
  loop: "{{ ext_node_details.results | default([]) }}"
  loop_control:
    loop_var: ext_node_item_data
    label: "{{ ext_node_item_name }} ({{ ext_node_item_state }})"
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ ext_node_title }} - set result (tmp)"
  set_fact:
    ext_node_result:
      hosts: "{{ ext_node_hosts }}"
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

# Set Result

- name: "{{ ext_node_title }} - set result"
  set_fact:
    cloud_service_result: "{{ ext_node_result }}"
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]
