- name: >-
    {{ ext_dns_title }} -
    [{{ ext_dns_record_type }}] {{ ext_dns_record }} -
    {{ ext_dns_value | default('') }} ({{ ext_dns_state }})
  cloudflare_dns:
    zone: "{{ ext_dns_zone }}"
    proxied: no
    solo: "{{ ext_dns_solo }}"
    type: "{{ ext_dns_record_type }}"
    record: "{{ ext_dns_record | default(omit, true) }}"
    value: "{{ ext_dns_value | default(omit, true) }}"
    ttl: "{{ ext_dns_ttl | default(ext_dns_inner_ttl | default(omit, true), true) }}"
    priority: "{{ ext_dns_priority | default(ext_dns_inner_priority | default(omit, true), true) }}"
    service: "{{ ext_dns_service | default(ext_dns_inner_service | default(omit, true), true) }}"
    proto: "{{ ext_dns_protocol | default(ext_dns_inner_protocol | default(omit, true), true) }}"
    port: "{{ ext_dns_port | default(ext_dns_inner_port | default(omit, true), true) }}"
    weight: "{{ ext_dns_weight | default(ext_dns_inner_weight | default(omit, true), true) }}"
    account_email: "{{ ext_dns_main_credentials.email }}"
    account_api_token: "{{ ext_dns_main_credentials.token }}"
    state: "{{ ext_dns_final_state }}"
