- name: >-
    {{ cloud_service_dns_title }} -
    [{{ cloud_service_dns_record_type }}] {{ cloud_service_dns_record }} -
    {{ cloud_service_dns_value | default('') }} ({{ cloud_service_dns_state }})
  cloudflare_dns:
    zone: "{{ cloud_service_params.zone | default(omit, true) }}"
    proxied: no
    solo: "{{ cloud_service_dns_solo }}"
    type: "{{ cloud_service_dns_record_type }}"
    record: "{{ cloud_service_dns_record | default(omit, true) }}"
    value: "{{ cloud_service_dns_value | default(omit, true) }}"
    account_email: "{{ cloud_service_dns_credentials.email }}"
    account_api_token: "{{ cloud_service_dns_credentials.token }}"
    state: "{{ cloud_service_dns_final_state }}"
