- name: >-
    {{ cloud_dns_title }} - cloudflare dns -
    [{{ cloud_dns_record_type }}] {{ cloud_dns_record }} -
    {{ cloud_dns_value | default('') }} ({{ cloud_dns_state }})
  cloudflare_dns:
    zone: "{{ cloud_dns_zone | default(omit, true) }}"
    proxied: no
    solo: "{{ cloud_dns_solo }}"
    type: "{{ cloud_dns_record_type }}"
    record: "{{ cloud_dns_record | default(omit, true) }}"
    value: "{{ cloud_dns_value | default(omit, true) }}"
    account_email: "{{ cloud_dns_credentials.email }}"
    account_api_token: "{{ cloud_dns_credentials.token }}"
    state: "{{ cloud_dns_final_state }}"
