root: "credentials"
schemas:
  credentials:
    type: "dict"
    props:
      dns:
        schema: "cloudflare_credentials"
        non_empty: true
  cloudflare_credentials:
    type: "dict"
    props:
      email:
        type: "str"
        non_empty: true
      token:
        type: "str"
        non_empty: true
