- name: "{{ ext_dns_title }} - define the new record"
  set_fact:
    ext_dns_record_data_aux:
      type: "{{ ext_dns_record_type }}"
      name: "{{ ext_dns_record }}"
      data: "{{ ext_dns_item.value | default('') }}"
      ttl: "{{ ext_dns_item.ttl | default('') }}"
      priority: "{{ ext_dns_item.priority | default('') }}"
      service: "{{ ext_dns_item.service | default('') }}"
      protocol: "{{ ext_dns_item.protocol | default('') }}"
      port: "{{ ext_dns_item.port | default('') }}"
      weight: "{{ ext_dns_item.weight | default('') }}"
  tags: ["no_print"]

- name: "{{ ext_dns_inner_title }} - empty record"
  set_fact:
    ext_dns_record_data: {}
  tags: ["no_print"]

- name: "{{ ext_dns_inner_title }} - define the record without empty fields"
  set_fact:
    ext_dns_record_data: >-
      {{
        ext_dns_record_data | combine({
          ext_dns_inner_item.key: ext_dns_inner_item.value
        })
      }}
  loop: "{{ ext_dns_record_data_aux | default({}) | dict2items | list }}"
  loop_control:
    loop_var: ext_dns_inner_item
    label: "{{ ext_dns_inner_item.key }}"
  when: ext_dns_inner_item.value != ''
  tags: ["no_print"]

- name: "{{ ext_dns_inner_title }} - define the record without empty fields"
  set_fact:
    ext_dns_record_data: >-
      {{
        ext_dns_record_data |
        combine({ 'ttl': ext_dns_record_data.ttl | default(600) | int })
      }}
  tags: ["no_print"]

- name:
  set_fact:
    ext_dns_records: "{{ ext_dns_records + [ext_dns_record_data] }}"
  tags: ["no_print"]
