root: "credentials"
schemas:
  credentials:
    type: "dict"
    props:
      dns:
        schema: "godaddy_credentials"
        non_empty: true
  godaddy_credentials:
    type: "dict"
    props:
      api_server:
        type: "str"
        non_empty: true
      api_version:
        type: "str"
        non_empty: true
      api_key:
        type: "str"
        non_empty: true
      api_secret:
        type: "str"
        non_empty: true
