root: "credentials"
schemas:
  credentials:
    type: "dict"
    props:
      dns:
        schema: "nsupdate_credentials"
        non_empty: true
  nsupdate_credentials:
    type: "dict"
    props:
      key_name:
        type: "str"
        non_empty: true
      key_secret:
        type: "str"
        non_empty: true
      key_algorithm:
        type: "str"
        non_empty: true
      server:
        type: "str"
        non_empty: true
