- name: >-
    {{ cloud_dns_title }} - nsupdate - create record -
    [{{ cloud_dns_record_type }}] {{ cloud_dns_record }}
  nsupdate:
    key_name: "{{ cloud_dns_credentials.key_name }}"
    key_secret: "{{ cloud_dns_credentials.key_secret }}"
    key_algorithm: "{{ cloud_dns_credentials.key_algorithm }}"
    server: "{{ cloud_dns_credentials.server }}"
    zone: "{{ cloud_dns_zone }}"
    type: "{{ cloud_dns_record_type }}"
    record: "{{ cloud_dns_record }}"
    value: "{{ cloud_dns_data_list | default([]) | map(attribute='value') }}"
    state: "{{ cloud_dns_state }}"
