root: "dns_params"
schemas:
  dns_params:
    type: "dict"
    props:
      zone:
        type: "str"
        non_empty: true
      dns_type:
        type: "str"
        non_empty: true
      record:
        type: "str"
        non_empty: true
      ttl:
        type: int
      priority:
        type: int
      service:
        type: str
      protocol:
        type: str
      port:
        type: int
      weight:
        type: int
      data_list:
        type: "list"
        elem_schema: "dns_item"
        elem_non_empty: "true"
  dns_item:
    type: "dict"
    props:
      value:
        type: str
        non_empty: true
      ttl:
        type: int
      priority:
        type: int
      service:
        type: str
      protocol:
        type: str
      port:
        type: int
      weight:
        type: int
