- name: "{{ inner_service_title }} - cloudflare dns - vars"
  lrd.ext_cloud.vars:
    identifier: "cloudflare_dns"
    raw_data:
      namespace: "ext_dns"
      state: "{{ inner_service_state }}"
      params: "{{ inner_service_params }}"
      credentials: "{{ inner_service_credentials }}"
      contents: "{{ inner_service_contents }}"
  register: ext_dns_data_wrapper
  tags: ["no_print"]

- name: "{{ inner_service_title }} - cloudflare dns - main"
  cloudflare_dns:
    zone: "{{ ext_dns_item.zone }}"
    proxied: no
    solo: "{{ ext_dns_item.solo }}"
    type: "{{ ext_dns_item.dns_type }}"
    record: "{{ ext_dns_item.record | default(omit, true) }}"
    value: "{{ ext_dns_item.value | default(omit, true) }}"
    ttl: "{{ ext_dns_item.ttl | default(omit, true) }}"
    priority: "{{ ext_dns_item.priority | default(omit, true) }}"
    service: "{{ ext_dns_item.service | default(omit, true) }}"
    proto: "{{ ext_dns_item.protocol | default(omit, true) }}"
    port: "{{ ext_dns_item.port | default(omit, true) }}"
    weight: "{{ ext_dns_item.weight | default(omit, true) }}"
    account_email: "{{ ext_dns_item.email }}"
    account_api_token: "{{ ext_dns_item.token }}"
    state: "{{ ext_dns_item.state }}"
  loop: "{{ ext_dns_data_wrapper.data.list }}"
  loop_control:
    loop_var: ext_dns_item
    label: >-
      [{{ ext_dns_item.state }}]
      {{ ext_dns_item.dns_type }}
      ({{ ext_dns_item.record }})
